# Generated by Django 5.2.4 on 2025-07-16 09:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('entrepreneur', 'Entrepreneur')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Enter your full name (letters, spaces, and dots only)', max_length=255, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, and dots', regex='^[a-zA-Z\\s.]+$')], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone number in format: +8801XXXXXXXXX or 01XXXXXXXXX', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +8801XXXXXXXXX or 01XXXXXXXXX', regex='^(\\+88)?01[0-9]{9}$')], verbose_name='phone number'),
        ),
    ]
