# Generated by Django 5.2.3 on 2025-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at_user_is_verified_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cds_admin', 'CDS Owner'), ('laundry_staff', 'Laundry Staff'), ('student', 'Student'), ('entrepreneur', 'Entrepreneur')], default='student', max_length=20),
        ),
    ]
