# Generated by Django 5.2.3 on 2025-07-19 17:46

from django.db import migrations, models


def update_cds_admin_to_cds_owner(apps, schema_editor):
    """Update existing cds_admin users to cds_owner"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='cds_admin').update(role='cds_owner')


def reverse_cds_owner_to_cds_admin(apps, schema_editor):
    """Reverse migration - update cds_owner back to cds_admin"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='cds_owner').update(role='cds_admin')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        # First update the data
        migrations.RunPython(
            update_cds_admin_to_cds_owner,
            reverse_cds_owner_to_cds_admin,
        ),
        # Then alter the field choices
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cds_owner', 'CDS Owner'), ('laundry_staff', 'Laundry Staff'), ('student', 'Student'), ('entrepreneur', 'Entrepreneur')], default='student', max_length=20),
        ),
    ]
