# Generated by Django 5.2.4 on 2025-07-16 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='NiggaTown', max_length=100)),
            ],
            options={
                'verbose_name': 'Storefront',
                'verbose_name_plural': 'Storefronts',
                'ordering': ['store_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, default='https://images.pexels.com/photos/789327/pexels-photo-789327.jpeg', null=True)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepreneurs_hub.storefront')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
