# Generated by Django 5.2.3 on 2025-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storefront',
            options={'ordering': ['store_id'], 'verbose_name': 'Storefront', 'verbose_name_plural': 'Storefronts'},
        ),
        migrations.AddField(
            model_name='storefront',
            name='name',
            field=models.CharField(default='NiggaTown', max_length=100),
        ),
    ]
