# Generated by Django 5.2.3 on 2025-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0002_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='name',
            field=models.CharField(default="IUTian's Waffle", max_length=100),
        ),
    ]
