# Generated by Django 5.2.3 on 2025-09-01 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='storefront',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='storefront',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='return_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='shipping_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='store_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='total_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='name',
            field=models.CharField(blank=True, default="IUTian's Waffle", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storefront',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='entrepreneurs_hub.owner'),
        ),
    ]
