# Generated by Django 5.2.3 on 2025-06-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='https://images.pexels.com/photos/789327/pexels-photo-789327.jpeg', null=True),
        ),
    ]
