# Generated by Django 5.2.3 on 2025-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0004_alter_storefront_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='image',
            field=models.URLField(default='https://images.pexels.com/photos/789327/pexels-photo-789327.jpeg'),
        ),
    ]
