# Generated by Django 5.2.5 on 2025-09-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0003_owner_storefront_created_at_storefront_description_and_more'),
        ('entrepreneurs_hub', '0004_alter_storefront_owner'),
    ]

    operations = [
    ]
