# Generated by Django 5.2.5 on 2025-09-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_owner_table(apps, schema_editor):
    """Create the Owner table manually if it doesn't exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'entrepreneurs_hub_owner'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            # Create the Owner table
            cursor.execute("""
                CREATE TABLE "entrepreneurs_hub_owner" (
                    "owner_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    "name" varchar(100) NOT NULL,
                    "image" varchar(200) NULL,
                    "bio" text NULL,
                    "phone" varchar(20) NULL,
                    "email" varchar(254) NULL,
                    "facebook_url" varchar(200) NULL,
                    "instagram_url" varchar(200) NULL,
                    "website_url" varchar(200) NULL,
                    "joined_date" timestamp with time zone NOT NULL
                );
            """)


def reverse_create_owner_table(apps, schema_editor):
    """Drop the Owner table"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS "entrepreneurs_hub_owner" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0005_merge_20250901_2030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Owner table using raw SQL
        migrations.RunPython(create_owner_table, reverse_create_owner_table),
        
        # Remove the current owner field (pointing to User)
        migrations.RemoveField(
            model_name='storefront',
            name='owner',
        ),
        
        # Add new owner field pointing to Owner model
        migrations.AddField(
            model_name='storefront',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='entrepreneurs_hub.owner'),
        ),
    ]
