# Generated by Django 5.2.3 on 2025-07-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0003_storefront_owner'),
        ('entrepreneurs_hub', '0006_alter_storefront_image'),
    ]

    operations = [
    ]
