# Generated by Django 5.2.3 on 2025-07-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs_hub', '0007_merge_20250721_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='name',
            field=models.CharField(default='NiggaTown', max_length=100),
        ),
    ]
