# Generated by Django 5.2.1 on 2025-06-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDS_Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, help_text='URL to item image', max_length=500, null=True)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CDS Item',
                'verbose_name_plural': 'CDS Items',
                'ordering': ['name'],
            },
        ),
    ]
