# Generated by Django 5.2.4 on 2025-09-02 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDS_Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True, help_text='URL to item image', max_length=500, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'CDS Item',
                'verbose_name_plural': 'CDS Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CDSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Pick Up'), ('bkash', 'bKash')], max_length=20)),
                ('delivery_status', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready')], default='preparing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CDSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cds.cdsorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cds.cds_item')),
            ],
        ),
    ]
