# Generated by Django 5.2.1 on 2025-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cds_item',
            options={'ordering': ['name'], 'verbose_name': 'CDS Item', 'verbose_name_plural': 'CDS Items'},
        ),
        migrations.AddField(
            model_name='cds_item',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cds_item',
            name='image',
            field=models.URLField(blank=True, help_text='URL to item image', max_length=500, null=True),
        ),
    ]
