# Generated by Django 5.2.1 on 2025-07-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cds_item',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
