# Generated by Django 5.2.1 on 2025-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_cdsorder_cdsorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdsorder',
            name='status',
        ),
        migrations.AddField(
            model_name='cdsorder',
            name='delivery_status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready')], default='preparing', max_length=20),
        ),
        migrations.AddField(
            model_name='cdsorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
